### ISSUE TITLE
how to depoly this frps in heroku?

### ISSUE THREAD

**Issue by alance123** [daviddwlee84/FRP-Heroku#1]

**Comment by daviddwlee84** [comment]
Just deploy the entire repository with some customized configuration change if you want.
But I haven't solved the limitation of Heroku that it doesn't allow custom port binding.

**Comment by alance123** [comment]
> binding

In the following github, https://github.com/jkutner/heroku-buildpack-ngrok, using the following command,
heroku config:set AUX_PORT=5001, can get a aux port, maybe it works.

**Comment by daviddwlee84** [comment]
Seem like it uses ngrok to do this feature. But the goal of my FRP is to expose my local ssh port. If I have to use ngrok, I might just use ngrok to expose my local port directly.
Anyway, thanks for the information.
