### ISSUE TITLE
How to connect heroku.

### ISSUE THREAD

**Issue by zhixuan2333** [daviddwlee84/FRP-Heroku#3]
I tryed 80,443...

**Comment by daviddwlee84** [comment]
#1 
It's not possible until Heroku can expose at least two ports.

**Comment by zhixuan2333** [comment]
but you can use xtcp or stcp..

**Comment by daviddwlee84** [comment]
Oh. I didn't know about that. I will have a look and see if there is any workaround.

**Comment by zhixuan2333** [comment]
sorry xtcp is not possible .
because heroku cannot use udp.

and can't use tcp.

**Comment by daviddwlee84** [comment]
Hmm, I see. That's okay.
